@startuml State_Player
interface PlayerState { +play(); +pause() }
class PlayingState
class PausedState
class Player { -state: PlayerState; +play(); +pause() }

PlayerState <|.. PlayingState
PlayerState <|.. PausedState
Player --> PlayerState
@enduml


